<a href="https://colab.research.google.com/github/Skshivu07/Titanic_dataset/blob/main/Numpy_assignement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)


Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Data Type: int64


In [ ]:
matrix_3x4 = np.arange(1, 13).reshape(3, 4)
print(matrix_3x4)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 51 makes the upper limit 50 inclusive
even_nums = np.arange(10, 51, 2)
print(even_nums)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
spaced_nums = np.linspace(0, 1, 10)
print(spaced_nums)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [ ]:
arr = np.array([1, 2, 3, 4])
print("Square:", arr ** 2)
print("Cube:", arr ** 3)


Square: [ 1  4  9 16]
Cube: [ 1  8 27 64]


In [ ]:
arr = np.array([100, 200, 300])
updated_arr = arr * 1.15
print(updated_arr)


[115. 230. 345.]


In [ ]:
a = np.array([5, 12, 8])
b = np.array([9, 3, 15])

print("Element-wise Max:", np.maximum(a, b))
print("Element-wise Min:", np.minimum(a, b))


Element-wise Max: [ 9 12 15]
Element-wise Min: [5 3 8]


In [ ]:
arr = np.arange(21)
print("First five:", arr[:5])
print("Last five:", arr[-5:])
print("Index 5 to 15:", arr[5:16])
print("Every second element:", arr[::2])


First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
arr = np.arange(10)
arr[:5] = 100
print(arr)


[100 100 100 100 100   5   6   7   8   9]


In [ ]:
original = np.array([1, 2, 3, 4, 5])

# Slice/View: Modifying the view changes the original array
view_arr = original[0:3]
view_arr[0] = 99
print("After view modification - Original:", original)

# Copy: Modifying the copy leaves the original array untouched
copy_arr = original.copy()
copy_arr[1] = 88
print("After copy modification - Original:", original)
print("Copy Array:", copy_arr)


After view modification - Original: [99  2  3  4  5]
After copy modification - Original: [99  2  3  4  5]
Copy Array: [99 88  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)


[5 4 3 2 1]


In [ ]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("Second row:", matrix[1, :])
print("Third column:", matrix[:, 2])
print("Element 50:", matrix[1, 1])


Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


In [ ]:
sub_matrix = matrix[0:2, 1:3]
print(sub_matrix)


[[20 30]
 [50 60]]


In [ ]:
m5x5 = np.arange(1, 26).reshape(5, 5)

print("First row:\n", m5x5[0, :])
print("Last column:\n", m5x5[:, -1])
print("Middle element:", m5x5[2, 2])
print("Top-left 3x3:\n", m5x5[0:3, 0:3])


First row:
 [1 2 3 4 5]
Last column:
 [ 5 10 15 20 25]
Middle element: 13
Top-left 3x3:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr = np.arange(10)
matrix_2x5 = arr.reshape(2, 5)
print(matrix_2x5)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
matrix_3x4 = np.arange(12).reshape(3, 4)
matrix_4x3 = matrix_3x4.T
print(matrix_4x3)


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
array_3d = np.arange(24).reshape(2, 3, 4)

# Reorders axes layout from (0,1,2) to (2,0,1)
transposed = array_3d.transpose(2, 0, 1)
# Swaps the first axis (0) and second axis (1)
swapped = array_3d.swapaxes(0, 1)

print("Transposed shape:", transposed.shape)
print("Swapped shape:", swapped.shape)


Transposed shape: (4, 2, 3)
Swapped shape: (3, 2, 4)


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.ones((3, 3)) * 2

print("Element-wise Addition:\n", A + B)
print("Element-wise Multiplication:\n", A * B)


Element-wise Addition:
 [[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
Element-wise Multiplication:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [ ]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(mat1, mat2)  # Alternatively: mat1 @ mat2
print(dot_product)


[[19 22]
 [43 50]]


In [ ]:
mat = np.array([[1, 2], [3, 4]])
mat_t = mat.T
result = np.dot(mat_t, mat)
print(result)


[[10 14]
 [14 20]]


In [ ]:
arr = np.array([4, 9, 16, 25])
print(np.sqrt(arr))


[2. 3. 4. 5.]


In [ ]:
arr = np.array([0, 1, 2])
print(np.exp(arr))


[1.         2.71828183 7.3890561 ]


In [ ]:
# Generating random values uniformly distributed between -2 and 5
rand_arr = np.random.uniform(-2, 5, 5)
print("Original:", rand_arr)
print("Absolute Values:", np.abs(rand_arr))
print("Exponential:", np.exp(rand_arr))
# We mask negative items to avoid runtime NaN errors during square root evaluations
print("Square Root (of abs value):", np.sqrt(np.abs(rand_arr)))


Original: [ 1.51472958 -1.39554325 -1.35564098  0.1733226   4.80734896]
Absolute Values: [1.51472958 1.39554325 1.35564098 0.1733226  4.80734896]
Exponential: [  4.54819102   0.24769844   0.25778201   1.18924969 122.40668195]
Square Root (of abs value): [1.23074351 1.18133114 1.16431996 0.41632031 2.19256675]


In [ ]:
arr1 = np.random.rand(5)
arr2 = np.random.rand(5)

print("Max values array:", np.maximum(arr1, arr2))


Max values array: [0.39549153 0.96434523 0.73949786 0.55139833 0.67392337]


In [ ]:
marks = np.array([35, 72, 48, 90, 55, 28])
updated_marks = np.where(marks < 40, 0, marks)
print(updated_marks)


[ 0 72 48 90 55  0]


In [ ]:
income = np.array([45000, 60000, 32000, 85000])
classification = np.where(income >= 50000, 'High', 'Low')
print(classification)


['Low' 'High' 'Low' 'High']


In [ ]:
arr = np.array([10, 25, 40, 15, 55])
result = np.where(arr > 30, 100, arr)
print(result)


[ 10  25 100  15 100]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Total Sum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Variance:", np.var(matrix))
print("Standard Deviation:", np.std(matrix))


Total Sum: 45
Mean: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("Row-wise Sums (axis=1):", np.sum(matrix, axis=1))
print("Column-wise Sums (axis=0):", np.sum(matrix, axis=0))


Row-wise Sums (axis=1): [ 6 15]
Column-wise Sums (axis=0): [5 7 9]


In [ ]:
student_marks = np.array([78, 85, 62, 91, 45, 88, 73, 69, 95, 54])

print("Mean:", np.mean(student_marks))
print("Std Dev:", np.std(student_marks))
print("Min:", np.min(student_marks))
print("Max:", np.max(student_marks))


Mean: 74.0
Std Dev: 15.728954192825409
Min: 45
Max: 95


In [ ]:
bool_arr = np.array([True, False, True])

print("Any (At least one is True):", np.any(bool_arr))
print("All (Every single item is True):", np.all(bool_arr))


Any (At least one is True): True
All (Every single item is True): False


In [ ]:
rand_nums = np.random.rand(10)
sorted_nums = np.sort(rand_nums)
print(sorted_nums)


[0.16693669 0.19853399 0.2227849  0.22996114 0.30032175 0.33731666
 0.48518036 0.77700507 0.9045683  0.91997908]


In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
print(np.unique(arr))


[1 2 3 4 5]


In [ ]:
marks = np.array([85, 90, 85, 70, 90, 65])
print(np.unique(marks))


[65 70 85 90]


In [ ]:
main_arr = np.array([10, 20, 30, 40, 50])
test_values = np.array([20, 60])

# Checks if elements of test_valt inside main_arr
mask = np.in1d(test_values, main_arr)
print(mask)  # Output: [True, False]


[ True False]


/tmp/ipykernel_648/2371341225.py:5: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  mask = np.in1d(test_values, main_arr)
